name: dart_gql_acsys
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.11.0

# Add regular dependencies here.
dependencies:
  ferry: ^0.16.2-dev.4
  gql_http_link: ^1.2.0
  gql_websocket_link: ^2.1.0
  gql_code_builder: ^0.15.0
  web_socket_channel: ^3.0.0
  built_collection: ^5.1.1
  built_value: ^8.9.5
  collection: ^1.19.1 # Use the latest version
  pure_dart_ui: ^0.1.10

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
  ferry_generator: ^0.14.0-dev.2
  build_runner: ^2.7.0
